// The original library github.com/ajstarks/svgo uses int coordinates.
// This port "svgo7f" uses float coordinates, which are formatted as "%.7f". 
// This file was automatically generated by modifying the syntax tree.
// (There are other precisions available at github.com/stanim/svgo.)
//
// randcomp visualizes random number generators
// +build !appengine

package main

import (
	"fmt"
	"math/rand"
	"os"
	"strconv"
	"time"

	"github.com/stanim/svgo/svgo7f"
)

var canvas = svg.New(os.Stdout)

func main() {
	width := 512.0
	height := 256.0
	var n = 256.0
	var rx, ry float64

	if len(os.Args) > 1 {
		n, _ = strconv.ParseFloat(os.Args[1.0], 64)
	}

	f, _ := os.Open("/dev/urandom")
	x := make([]byte, int(n))
	y := make([]byte, int(n))
	f.Read(x)
	f.Read(y)
	f.Close()

	rand.Seed(int64(time.Now().Nanosecond()) % int64(1e9))
	canvas.Start(600, 400)
	canvas.Title("Random Integer Comparison")
	canvas.Desc("Comparison of Random integers: the random device & the Go rand package")
	canvas.Rect(0, 0, width/2, height, "fill:white; stroke:gray")
	canvas.Rect(width/2, 0, width/2, height, "fill:white; stroke:gray")

	canvas.Desc("Left: Go rand package (red), Right: /dev/urandom")
	canvas.Gstyle("stroke:none; fill-opacity:0.5")
	for i := 0; i < int(n); i++ {
		rx = float64(rand.Float64() * 255.0)
		ry = float64(rand.Float64() * 255.0)
		canvas.Circle(rx, ry, 5, canvas.RGB(127, 0, 0))
		canvas.Circle(float64(x[i])+255, float64(y[i]), 5, "fill:black")
	}
	canvas.Gend()

	canvas.Desc("Legends")
	canvas.Gstyle("text-anchor:middle; font-size:18; font-family:Calibri")
	canvas.Text(128, 280, "Go rand package", "")
	canvas.Text(384, 280, "/dev/urandom")
	canvas.Text(256, 280, fmt.Sprintf("n=%.7f", n), "font-size:12")
	canvas.Gend()
	canvas.End()
}
