// The original library github.com/ajstarks/svgo uses int coordinates.
// This port "svgo5f" uses float coordinates, which are formatted as "%.5f". 
// This file was automatically generated by modifying the syntax tree.
// (There are other precisions available at github.com/stanim/svgo.)
//
// marker test
// +build !appengine

package main

import (
	"github.com/stanim/svgo/svgo5f"
	"os"
)

func main() {
	canvas := svg.New(os.Stdout)
	canvas.Start(500, 500)
	canvas.Title("Marker")

	canvas.Def()
	canvas.Marker("dot", 5, 5, 8, 8)
	canvas.Circle(5, 5, 3, "fill:black")
	canvas.MarkerEnd()

	canvas.Marker("box", 5, 5, 8, 8)
	canvas.CenterRect(5, 5, 6, 6, "fill:green")
	canvas.MarkerEnd()

	canvas.Marker("arrow", 2, 6, 13, 13)
	canvas.Path("M2,2 L2,11 L10,6 L2,2", "fill:blue")
	canvas.MarkerEnd()
	canvas.DefEnd()

	x := []float64{100.0, 250.0, 100.0}
	y := []float64{100.0, 250.0, 400.0}
	canvas.Polyline(x, y,
		`fill="none"`,
		`stroke="red"`,
		`marker-start="url(#dot)"`,
		`marker-mid="url(#arrow)"`,
		`marker-end="url(#box)"`)
	canvas.End()
}
