// The original library github.com/ajstarks/svgo uses int coordinates.
// This port "svgo2f" uses float coordinates, which are formatted as "%.2f". 
// This file was automatically generated by modifying the syntax tree.
// (There are other precisions available at github.com/stanim/svgo.)
//
// skewabc - exercise the skew functions
// +build !appengine

package main

import (
	"fmt"
	"os"

	"github.com/stanim/svgo/svgo2f"
)

var (
	g      = svg.New(os.Stdout)
	width  = 500.0
	height = 500.0
)

func sky(x, y, w, h float64, a float64, s string) {
	g.Gstyle(fmt.Sprintf("font-family:sans-serif;font-size:%.2fpx;text-anchor:middle", w/2))
	g.SkewY(a)
	g.Rect(x, y, w, h, `fill:black; fill-opacity:0.3`)
	g.Text(x+w/2, y+h/2, s, `fill:white;baseline-shift:-33%`)
	g.Gend()
	g.Gend()
}

func main() {
	g.Start(width, height)
	g.Title("Skew")
	g.Rect(0, 0, width, height, "fill:white")
	g.Grid(0, 0, width, height, 50, "stroke:lightblue")
	sky(100, 100, 100, 100, 30, "A")
	sky(200, 332, 100, 100, -30, "B")
	sky(300, -15, 100, 100, 30, "C")
	g.End()
}
