// The original library github.com/ajstarks/svgo uses int coordinates.
// This port "svgof" uses float coordinates, which are formatted as "%f". 
// This file was automatically generated by modifying the syntax tree.
// (There are other precisions available at github.com/stanim/svgo.)
//
package main

// Imports
import (
	"encoding/xml"
	"flag"
	"fmt"
	"github.com/stanim/svgo/svgof"
	"io"
	"os"
)

// <thing top="100" left="100" sep="100">
//    <item width="50"  height="50"  name="Little" color="blue">This is small</item>
//    <item width="75"  height="100" name="Med"    color="green">This is medium</item>
//    <item width="100" height="200" name="Big"    color="red">This is large</item>
// </thing>

type Thing struct {
	Top  float64 `xml:"top,attr"`
	Left float64 `xml:"left,attr"`
	Sep  float64 `xml:"sep,attr"`
	Item []item  `xml:"item"`
}

type item struct {
	Width  float64 `xml:"width,attr"`
	Height float64 `xml:"height,attr"`
	Name   string  `xml:"name,attr"`
	Color  string  `xml:"color,attr"`
	Text   string  `xml:",chardata"`
}

var (
	width  = flag.Float64("w", 1024, "width")
	height = flag.Float64("h", 768, "height")
	canvas = svg.New(os.Stdout)
)

// Open the file
func dothing(location string) {
	f, err := os.Open(location)
	if err != nil {
		fmt.Fprintf(os.Stderr, "%v\n", err)
		return
	}
	defer f.Close()
	readthing(f)
}

// Read the file, loading the defined structure
func readthing(r io.Reader) {
	var t Thing
	if err := xml.NewDecoder(r).Decode(&t); err != nil {
		fmt.Fprintf(os.Stderr, "Unable to parse components (%v)\n", err)
		return
	}
	drawthing(t)
}

// use the items of "thing" to make the picture
func drawthing(t Thing) {
	x := t.Left
	y := t.Top
	for _, v := range t.Item {
		style := fmt.Sprintf("font-size:%fpx;fill:%s", v.Width/2.0, v.Color)
		canvas.Circle(x, y, v.Height/4, "fill:"+v.Color)
		canvas.Text(x+t.Sep, y, v.Name+":"+v.Text+"/"+v.Color, style)
		y += v.Height
	}
}

func main() {
	flag.Parse()
	for _, f := range flag.Args() {
		canvas.Start(*width, *height)
		dothing(f)
		canvas.End()
	}
}
