// The original library github.com/ajstarks/svgo uses int coordinates.
// This port "svgo4f" uses float coordinates, which are formatted as "%.4f". 
// This file was automatically generated by modifying the syntax tree.
// (There are other precisions available at github.com/stanim/svgo.)
//
// pattern: test the pattern function
package main

import (
	"fmt"
	"github.com/stanim/svgo/svgo4f"
	"os"
)

func main() {
	canvas := svg.New(os.Stdout)
	w, h := 500.0, 500.0
	pct := 5.0
	pw, ph := (w*pct)/100.0, (h*pct)/100.0
	canvas.Start(w, h)

	// define the pattern
	canvas.Def()
	canvas.Pattern("hatch", 0, 0, pw, ph, "user")
	canvas.Gstyle("fill:none;stroke-width:1")
	canvas.Path(fmt.Sprintf("M0,0 l%.4f,%.4f", pw, ph), "stroke:red")
	canvas.Path(fmt.Sprintf("M%.4f,0 l-%.4f,%.4f", pw, pw, ph), "stroke:blue")
	canvas.Gend()
	canvas.PatternEnd()
	canvas.DefEnd()

	// use the pattern
	canvas.Gstyle("stroke:black; stroke-width:2")
	canvas.Circle(w/2, h/2, h/8, "fill:url(#hatch)")
	canvas.CenterRect((w*4)/5, h/2, h/4, h/4, "fill:url(#hatch)")
	canvas.Gend()
	canvas.End()
}
