// The original library github.com/ajstarks/svgo uses int coordinates.
// This port "svgo2f" uses float coordinates, which are formatted as "%.2f". 
// This file was automatically generated by modifying the syntax tree.
// (There are other precisions available at github.com/stanim/svgo.)
//
// svgrid -- composite SVG files in a grid
// +build !appengine

package main

import (
	"encoding/xml"
	"flag"
	"fmt"
	"io"
	"os"

	"github.com/stanim/svgo/svgo2f"
)

// SVG is a SVG document
type SVG struct {
	Width  string `xml:"width,attr"`
	Height string `xml:"height,attr"`
	Doc    string `xml:",innerxml"`
}

var (
	byrow                                          bool
	startx, starty, count, gutter, gwidth, gheight float64
	canvas                                         = svg.New(os.Stdout)
)

// init sets up command line options
func init() {
	flag.BoolVar(&byrow, "r", true, "order row wise")
	flag.Float64Var(&startx, "x", 0, "begin x")
	flag.Float64Var(&starty, "y", 0, "begin y")
	flag.Float64Var(&count, "c", 3, "columns or rows")
	flag.Float64Var(&gutter, "g", 100, "gutter")
	flag.Float64Var(&gwidth, "w", 1024, "width")
	flag.Float64Var(&gheight, "h", 768, "height")
	flag.Parse()
}

// placepic puts a SVG file at a location
func placepic(x, y float64, filename string) (float64, float64) {
	var (
		s             SVG
		width, height float64
		wunit, hunit  string
	)
	f, err := os.Open(filename)
	if err != nil {
		fmt.Fprintf(os.Stderr, "%v\n", err)
		return 0, 0
	}
	defer f.Close()
	if err := xml.NewDecoder(f).Decode(&s); err != nil {
		fmt.Fprintf(os.Stderr, "Unable to parse (%v)\n", err)
		return 0, 0
	}

	// read the width and height, including any units
	// if there are errors use 10 as a default
	nw, _ := fmt.Sscanf(s.Width, "%.2f%s", &width, &wunit)
	if nw < 1 {
		width = 10.0
	}
	nh, _ := fmt.Sscanf(s.Height, "%.2f%s", &height, &hunit)
	if nh < 1 {
		height = 10.0
	}
	canvas.Group(`clip-path="url(#pic)"`, fmt.Sprintf(`transform="translate(%.2f,%.2f)"`, x, y))
	canvas.ClipPath(`id="pic"`)
	canvas.Rect(0, 0, width, height)
	canvas.ClipEnd()
	io.WriteString(canvas.Writer, s.Doc)
	canvas.Gend()
	return width, height
}

// compose places files row or column-wise
func compose(x, y, n float64, rflag bool, files []string) {
	px := x
	py := y
	var pw, ph float64
	for i, f := range files {
		if i > 0 && i%int(n) == 0 {
			if rflag {
				px = x
				py += gutter + ph
			} else {
				px += gutter + pw
				py = y
			}
		}
		pw, ph = placepic(px, py, f)
		if rflag {
			px += gutter + pw
		} else {
			py += gutter + ph
		}
	}
}

// main lays out files as specified on the command line
func main() {
	canvas.Start(gwidth, gheight)
	compose(startx, starty, count, byrow, flag.Args())
	canvas.End()
}
